NAME = test

CC = gcc
LD = ld
KPACK = kpack

SRC = test.c
CFLAGS = -m32 -c -nostdinc -I ../source/include
LDFLAGS = -m elf_i386 -T static.lds -nostdlib -L ../bin/lib

all:
	$(CC) $(CFLAGS) $(NAME).c
	$(LD) $(LDFLAGS) $(NAME).o -o $(NAME) -lc
	objcopy $(NAME) -O binary
	$(KPACK) $(NAME) 

clean:
	rm $(NAME)
