NAME = test

CC = gcc
LD = ld
KPACK = kpack --nologo

SRC = test.c
CFLAGS = -m32 -c -nostdinc -I ../source/include -fno-stack-protector -ffreestanding -fno-pie
LDFLAGS = -m elf_i386 -T static.lds -nostdlib ../bin/lib/crt0.o -L ../bin/lib 

all:
	$(CC) $(CFLAGS) $(NAME).c
	$(LD) $(LDFLAGS) $(NAME).o -o $(NAME) -lc
	strip -s $(NAME) -o $(NAME)
	objcopy $(NAME) -O binary
	$(KPACK) $(NAME) 

clean:
	rm $(NAME).o
