CC = ../linuxtools/kgcc
LD = ../linuxtools/kld

SRC = $(NAME).c

.PHONY: all

all: $(NAME)

$(NAME): $(SRC)
	$(CC) -O2 $(SRC)
	$(LD) $(NAME).o -o $(NAME) -lc
	strip -s $(NAME) -o $(NAME)
	objcopy $(NAME) -O binary

clean:
	rm $(NAME).o $(NAME)
