CC = gcc
LD = ld
KPACK = kpack --nologo

SRC = $(NAME).c
CFLAGS = -m32 -c -nostdinc -I ../source/include -Os -fno-common -fno-builtin -fno-stack-protector -fno-pie
LDFLAGS = -m elf_i386 -T static.lds -nostdlib ../bin/lib/crt0.o -L ../bin/lib 

.PHONY: all

all: $(NAME)

$(NAME): $(SRC)
	$(CC) $(CFLAGS) $(SRC)
	$(LD) $(LDFLAGS) $(NAME).o -o $(NAME) -lc
	strip -s $(NAME) -o $(NAME)
	objcopy $(NAME) -O binary
	$(KPACK) $(NAME) 

clean:
	rm $(NAME).o $(NAME)
