#!/bin/bash
set -e

AR=ar
FASM=fasm

set -e

cd $1

echo "Compile ASM files..."
for asm_file in $(find *.asm) 
do
    $FASM $asm_file >> /dev/null
done

echo "Create libc.obj.a library..."
rm -rf ../lib/libc.obj.a
ar -rsc ../lib/libc.obj.a *.o
mv __lib__.asm __lib__.asm.bak
rm -f *.o *.asm
mv __lib__.asm.bak __lib__.asm
echo "Done!"
