name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: chmod u+x $PWD/bin/fasm && export PATH=$PATH:$PWD/bin && echo $PATH && cd source && make
